name = "spinogambinocasino-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinogambinocasino.pt"
HMAC_KEY = "7488779b66d5e216827d2b2163c21e13552c570abc8854d3553c6ef903575b5f"
COOKIE_NAME = "g7n"
PLAY_PATH = "explore"
BUTTON_ID = "peefd668640988eb16049c9df07cf6b29"
GATE_SALT = "4f60de4ba8067d6f"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "78ky"
CTA_SELECTOR = ".play-button"
